version: "2.26.1"

services:
  django:
    build:
      context: ./
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: software_testing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6862
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge
