# Generated by Django 5.0.3 on 2024-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SoftwareTesting_Selenium_Docker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('ListItems', models.TextField()),
                ('Image', models.CharField(max_length=50)),
                ('HistorySubTitle', models.CharField(max_length=100)),
                ('HistoryTitle', models.CharField(max_length=100)),
                ('HistoryTimeLineYear', models.CharField(max_length=25)),
                ('HistoryTimeLineDescription', models.TextField(max_length=250)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
