# Generated by Django 5.0.3 on 2024-05-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareTesting_Selenium_Docker', '0002_initial'),
    ]

    operations = [
    ]
